#!/usr/bin/env python

import shlex
import sys
import xml.etree.ElementTree as etree
from datetime import datetime
from subprocess import check_output

limit = sys.argv[1] if len(sys.argv) > 1 else 10
log = check_output(shlex.split('svn log --xml -l {}'.format(limit)))
root = etree.fromstring(log)

for entry in root:
    rev = entry.attrib['revision']
    author = entry.find('author').text
    datestr = entry.find('date').text
    date = datetime.strptime(datestr, '%Y-%m-%dT%H:%M:%S.%fZ').strftime('%b %-d %Y')
    msg = entry.find('msg').text
    if msg:
        msg = msg.splitlines()[0]

    sys.stdout.write('\033[31m{}\033[0m - {} \033[32m({})\033[0m \033[34m<{}>\033[0m\n'.format(rev, msg, date, author))
